# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'test'     
        required: false
        default: 'test'
      tags:
        description: 'test' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: setup
        run: ./setup.sh
      
      - name: update
        run: ./update_trusty.sh
