# This is a basic workflow to help you get started with Actions

name: Update Event Bridge images 

on:
  schedule:
  - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'test'     
        required: false
        default: 'test'
      tags:
        description: 'test' 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: chmod
        run: |
          chmod +x event-bridge/setup.sh
          chmod +x event-bridge/patch.py
          chmod +x event-bridge/get_latest_image_version.py
          chmod +x event-bridge/update_images.sh
      # Runs a single command using the runners shell
      - name: setup
        run: ./event-bridge/setup.sh
        env: 
          GH_USER: ${{ secrets.GH_USER }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          MY_KEY: ${{ secrets.MY_KEY }}

      # Runs a set of commands using the runners shell
      - name: update
        run: ./event-bridge/update_images.sh
        env: 
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
