name: Manager - CI
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
    branches:    
      - 'main'
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        if: !contains(github.event.pull_request.labels.*.name, 'safe to test')
        run: |
          echo "you have to add the label"
          exit 1
      - name: Print operator log
        if: always()
        run: |
          kubectl logs deployment/event-bridge-shard-operator -n event-bridge-operator
      - name: Print manager log
        if: always()
        run: |
          kubectl logs deployment/event-bridge -n event-bridge-manager
